#!/bin/sh

trap "" HUP
trap "" TERM
[ ! -d /var/run/proftpd ] && mkdir /var/run/proftpd
[ ! -f /var/log/wtmp ] && touch /var/log/wtmp

# Written by Scripts/unharden.sh; each card switch adds one -D define.
UNHARDEN=/media/fat/linux/unharden

start() {
	set --
	mode="hardened: no root login"
	if [ -e "$UNHARDEN" ]; then
		set -- "$@" -D MISTER_UNHARDENED
		mode="UNHARDENED: root login on"
	fi
	printf "Starting ProFTPD: "
	if ! /usr/sbin/proftpd "$@"; then
		echo "FAILED"
		exit 1
	else
		echo "done ($mode)"
	fi
}

stop() {
	printf "Stopping ProFTPD: "
	killall proftpd
        echo "done"
}

case "$1" in
    start)
	start
	;;

    stop)
	stop
	;;

    restart)
    	stop
    	start
	;;

    *)
	echo "Usage: /etc/init.d/S50proftpd {start|stop|restart}"
	exit 1
	;;
esac

exit 0
