pcm.!default
{
    type plug
    slave.pcm
    {
        type rate
        slave
        {
            format S16_LE
            rate 48000
            pcm
            {
                type file
                file "/dev/MrAudio"
                format "raw"
                slave.pcm
                {
                    type hw
                    card 0
                }
            }
        }
    }
}

pcm.front pcm.default
